import os
from django.conf import settings
import urllib.parse

def obtener_tipos_documentos_por_codigo_entidad():
    tipos_documentos_por_codigo_entidad = {
        'SAN01':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'SAN02':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'POL12':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'PML01':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'COM01': ['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'CAJACO':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'CAJASU':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'SAL01':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'CAP01':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'UNA01':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'DM02':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'EQV01':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'PAR01':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'CHM05':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'CHM02': ['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'COL01':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'MES01': ['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
        'POL11':['FACTURA', 'COMPROBANTE','AUTORIZACION','ORDEN','ADICIONALES','RESULTADO','HISTORIACLINICA',],
    }
    return tipos_documentos_por_codigo_entidad

def obtener_tipos_documentos_por_entidad(codigo_entidad):
    tipos_documentos_por_codigo_entidad = obtener_tipos_documentos_por_codigo_entidad()
    return tipos_documentos_por_codigo_entidad.get(codigo_entidad, [])


