# Generated by Django 5.0.1 on 2024-06-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_usuario_antares',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='usuario_antares',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
