# Generated by Django 5.0.1 on 2024-02-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivofacturacion',
            name='Observacion',
            field=models.CharField(default='sin_nombre', max_length=255),
        ),
        migrations.AddField(
            model_name='archivofacturacion',
            name='RevisionPrimera',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivofacturacion',
            name='RevisionSegunda',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='archivofacturacion',
            name='RevisionTercera',
            field=models.BooleanField(default=False),
        ),
    ]
