# Generated by Django 5.0.1 on 2024-05-29 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivofacturacion',
            name='Usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observacionesarchivos',
            name='ObservacionCuentasMedicas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='observacionesarchivos',
            name='ObservacionTesoreria',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='archivofacturacion',
            name='Tipo',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
