# Generated by Django 5.0.1 on 2024-02-26 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TiposDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoEntidad', models.CharField(max_length=20, unique=True)),
                ('Documentos', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='archivofacturacion',
            name='Tipo',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
