# Generated by Django 5.0.1 on 2024-01-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0002_factura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivofacturacion',
            name='NombreArchivo',
            field=models.CharField(default='sin_nombre', max_length=255),
        ),
    ]
