# Generated by Django 5.0.1 on 2024-06-13 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0002_archivofacturacion_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivofacturacion',
            name='RutaArchivo',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='gdocumental/archivosFacturacion'),
        ),
    ]
