# Generated by Django 5.0.1 on 2024-02-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0003_alter_archivofacturacion_fechacreacionarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaCuentasMedicas',
            fields=[
                ('AdmisionId', models.IntegerField(primary_key=True, serialize=False)),
                ('FechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('FechaCargurArchivo', models.DateTimeField(auto_now_add=True)),
                ('RevisionCuentasMedicas', models.BooleanField(default=False)),
                ('RevisionTesoreria', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'AdmisionAuditoria',
                'managed': True,
            },
        ),
    ]
