# Generated by Django 5.0.1 on 2024-07-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0003_alter_archivofacturacion_rutaarchivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivofacturacion',
            name='FechaCreacionAntares',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
