# Generated by Django 5.0.1 on 2024-07-07 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0004_archivofacturacion_fechacreacionantares'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivofacturacion',
            name='Regimen',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='archivofacturacion',
            name='UsuarioCuentasMedicas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_medicas_archivos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivofacturacion',
            name='UsuariosTesoreria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesoreria_archivos', to=settings.AUTH_USER_MODEL),
        ),
    ]
