# Generated by Django 5.0.1 on 2024-02-07 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0004_auditoriacuentasmedicas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoriacuentasmedicas',
            old_name='FechaCargurArchivo',
            new_name='FechaCargueArchivo',
        ),
    ]
