# Generated by Django 5.0.1 on 2024-02-08 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0005_rename_fechacargurarchivo_auditoriacuentasmedicas_fechacarguearchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionesArchivos',
            fields=[
                ('IdObservacion', models.AutoField(primary_key=True, serialize=False)),
                ('FechaObservacion', models.DateTimeField(auto_now_add=True)),
                ('Descripcion', models.CharField(default='', max_length=255)),
                ('IdArchivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='gedocumental.archivofacturacion')),
            ],
            options={
                'db_table': 'ObservacionArchivo',
                'managed': True,
            },
        ),
    ]
