# Generated by Django 5.0.1 on 2024-07-09 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0005_add_revisada_to_observacionsinarchivo'),
        ('gedocumental', '0006_observacionsinarchivo'),
    ]

    operations = [
    ]
