# Generated by Django 5.0.1 on 2024-02-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0006_observacionesarchivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observacionesarchivos',
            name='Descripcion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
