# Generated by Django 5.0.1 on 2024-02-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0006_observacionesarchivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivofacturacion',
            name='Observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
