# Generated by Django 5.0.1 on 2024-07-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0007_merge_20240709_1836'),
    ]

