# Generated by Django 5.0.1 on 2024-07-13 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0008_archivofacturacion_radicado'),
    ]

    operations = [
      
    ]
