# Generated by Django 5.0.1 on 2024-08-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0009_archivofacturacion_idrevisor_and_more'),
    ]


