# Generated by Django 5.0.1 on 2024-08-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0010_archivofacturacion_fecharevisionprimera'),
    ]

    operations = [
    
     
     
 
    ]
