# Generated by Django 5.0.1 on 2024-09-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gedocumental', '0012_archivofacturacion_fecharevisionprimera_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrdenHis', models.CharField(max_length=20, unique=True)),
                ('NombreUsuario', models.CharField(max_length=100)),
                ('ApellidoUsuario', models.CharField(max_length=100)),
                ('Documento', models.CharField(max_length=20)),
                ('TipoDocumento', models.CharField(max_length=5)),
                ('Observaciones', models.TextField()),
                ('FechaServicio', models.DateField()),
                ('NombreProfesional', models.CharField(max_length=100)),
                ('NombreServicio', models.CharField(max_length=100)),
                ('IdentificacionProfesional', models.CharField(max_length=20)),
            ],
        ),
       
    ]
